[theme]
# A dark-blue primary accent color for interactive elements
primaryColor = "#794F37"

# A light "white-blue" background color for the main content area
backgroundColor = "#d3bd9b"

# A lighter background color for the sidebar and other components
secondaryBackgroundColor = "#DED6C7"

# A darker text color for better contrast against the light background
textColor = "#2C2223"
